// Site configuration - auto-generated by scan-media.js
// Last updated: 2025-07-23T04:08:44.948Z
const siteConfig = {
    "audio": {
        "Mastering-Examples": [
            "FRAGMENT-1 -(UN-MASTERED).wav",
            "FRAGMENT-1-(FINAL-MIX).wav",
            "FRAGMENT-1-(MASTERED).wav",
            "FRAGMENT-2-(FINAL-MIX).wav",
            "FRAGMENT-2-(MASTERED).wav",
            "FRAGMENT-2-(UN-MASTERED).wav",
            "FRAGMENT-3-(FINAL-MIX).wav",
            "FRAGMENT-3-(MASTERED).wav",
            "FRAGMENT-3-(UN-MASTERED).wav",
            "FRAGMENT-4-(FINAL-MIX).wav",
            "FRAGMENT-4-(MASTERED).wav",
            "FRAGMENT-4-(UN-MASTERED).wav",
            "FRAGMENT-5-(FINAL-MIX).wav",
            "FRAGMENT-5-(MASTERED).wav",
            "FRAGMENT-5-(UN-MASTERED).wav"
        ],
        "Audio-Restoration-Examples": [
            "FRAGMENT01 (REPAIRED).wav",
            "FRAGMENT01 (UN-REPAIRED).wav",
            "FRAGMENT02 (REPAIRED).wav",
            "FRAGMENT02 (UN-REPAIRED).wav"
        ]
    },
    "VIDEO": {
        "Collaboration": [
            "El Vega, Ladronn, DJ Jac - CARNE VIVA - LilSilvioElVegaVEVO (1080p, h264, youtube).mp4",
            "HAPPY - LA FACTORIA ALEXIS (VIDEO OFICIAL).mp4",
            "Karly Way & El Oveja  - El Trompo   Video Oficial - Rocha Disc (1080p, h264, youtube).mp4",
            "ROXXXE - La Factoria  (Video Oficial).mp4",
            "Simon Olano X Luisk De Leon - Culpo Al Alcohol.mp4",
            "Valderrama X BLACKIEBWOY - Hablan de Mi (Audio Oficial) - Valderrama Oficial (1080p, h264, youtube).mp4"
        ],
        "Mastering": [
            "2022-01-17.mp4",
            "2022-03-31.mp4",
            "POP-3.mp4",
            "pop4.mp4"
        ],
        "Restoration": [
            "optometra.mp4"
        ]
    }
};
